/** Loads the app and its Go back, links each front HTTP call to its back route, and holds the report helpers. */
import { execSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { basename, join, relative, resolve, sep } from 'node:path';
import { readBack, resolveBackDir, routeKey } from './back.mjs';
import { buildCallGraph, loadFront, readHttpCall } from './front.mjs';

/** The app being audited: the working directory (make / npm run from the repo root), or AUDIT_ROOT. */
export const FRONT_ROOT = resolve(process.env.AUDIT_ROOT ?? process.cwd());
export const APP_NAME = basename(FRONT_ROOT);
export const OUT_DIR = join(FRONT_ROOT, 'tmp', 'api');

/**
 * calls: every `r` / `rPublic` call — { nodeId, http, key, route } where route is null when the back
 * has no such route (or the URL is external / not statically known).
 * With `optionalBack`, a missing back gives `backDir: null` and no routes instead of throwing; `withBack: false`
 * skips it altogether.
 */
export const loadAll = ({ optionalBack = false, withBack = true } = {}) => {
  let backDir = null;
  try {
    backDir = withBack ? resolveBackDir(FRONT_ROOT) : null;
  } catch (error) {
    if (!optionalBack) {
      throw error;
    }
  }
  const routes = backDir ? readBack(backDir) : [];
  const routeByKey = new Map(routes.map((route) => [route.key, route]));

  const front = loadFront(FRONT_ROOT);
  const nodes = buildCallGraph(front);

  const calls = [];
  for (const node of nodes.values()) {
    for (const call of node.httpCalls) {
      const http = readHttpCall(front, call);
      const key = http.url && !/^https?:\/\//.test(http.url) ? routeKey(http.method, http.url) : null;
      calls.push({ nodeId: node.id, http, key, route: key ? (routeByKey.get(key) ?? null) : null });
    }
  }
  return { backDir, front, nodes, routes, calls };
};

// ─── Markdown ────────────────────────────────────────────────────────────────

const gitState = (dir) => {
  try {
    const sha = execSync('git rev-parse --short HEAD', { cwd: dir, encoding: 'utf8' }).trim();
    const dirty = execSync('git status --porcelain', { cwd: dir, encoding: 'utf8' }).trim() !== '';
    return `\`${sha}\`${dirty ? ' + uncommitted changes' : ''}`;
  } catch {
    return 'unknown';
  }
};

export const header = (title, command, ctx) => {
  const now = new Date().toISOString().slice(0, 16).replace('T', ' ');
  return [
    `# ${title}`,
    '',
    `> Generated by \`${command}\` on ${now} — do not edit by hand, re-run the command.`,
    `> Front ${gitState(FRONT_ROOT)} · back ${gitState(ctx.backDir)} (\`${relative(FRONT_ROOT, ctx.backDir)}\`)`,
    '',
  ].join('\n');
};

/** `[label](relative/path#L12)` to a front or back location, relative to the report folder. */
export const link = (ctx, loc, label) => {
  if (!loc) {
    return label ?? '?';
  }
  const abs = join(loc.repo === 'back' ? ctx.backDir : FRONT_ROOT, loc.file);
  const target = relative(OUT_DIR, abs).split(sep).join('/');
  return `[${label ?? `${loc.file}:${loc.line}`}](${target}#L${loc.line})`;
};

export const code = (text) => `\`${String(text).replace(/`/g, "'")}\``;

export const cell = (text) => String(text).replace(/\|/g, '\\|').replace(/\n/g, ' ');

export const writeReport = (fileName, content) => {
  mkdirSync(OUT_DIR, { recursive: true });
  const path = join(OUT_DIR, fileName);
  writeFileSync(path, `${content.trim()}\n`);
  return relative(FRONT_ROOT, path);
};
